name: Mike's Simple Example

on: [pull_request]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
# https://octanner.atlassian.net/wiki/spaces/PLAT/pages/302187013/GitHub+Actions+Workshop#Create-workflow